### ISSUE TITLE
Program attached itself to a different game; text won't go away

### ISSUE THREAD

**Issue by syruppp** [monpjc/XAHK#27] opened 2020-08-31 00:47 UTC
XAHK attached itself to the Elder Scrolls Online, and the text "Turn Off This Memo: Ctrl+Alt+W" is stuck on the screen and even appears in in-game screenshots. I've tried restarting my PC, clearing temporary files, but it's still there. I even tried running a repair on the game itself.
![image](https://user-images.githubusercontent.com/45257555/91673410-9e312a80-eaf9-11ea-9aa7-3244eab4ca09.png)

**Comment by histefanhere** [comment] 2022-02-22 23:17
Wowza, interesting! Really not sure what's the cause of this and I hope you've fixed it. My best guess is maybe `ctrl+alt+w` is a hotkey used in Elder Scrolls Online and there was some sort of conflict? ¯\_(ツ)_/¯. I'm going to close this issue but I'll keep this in mind if it arises again in the future.

**Closed as completed by histefanhere** 2022-02-22 23:17 UTC
